Added a test to reproduce the bug in https://github.com/mevansam/terraform-provider-cf/issues/88 (#1)
If the PR is not applied, after running this test many times, it should crash with this error
=== RUN   TestAccApp_reproduceIssue88
Application downloaded to: ../tests/cf-acceptance-tests/assets/java-spring/
Application downloaded to: ../tests/cf-acceptance-tests/assets/java-spring/
fatal error: concurrent map read and map write

goroutine 1542 [running]:
...
created by github.com/terraform-providers/terraform-provider-cf/cloudfoundry.resourceAppCreate
.../golang/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/resource_cf_app.go:421 +0x1ac4

# Conflicts:
#	cloudfoundry/resource_cf_app_test.go